version: '3'
services:

  backend:
    image: "backend-image"
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - demo-network

  frontend:
    image: "frontend-image"
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - demo-network


networks:
  demo-network:
    driver: bridge