export const data = [
  {
    id: 1,
    make: "Toyota",
    model: "Corolla",
    year: 2022,
    color: "Blue",
    mileage: 20000,
    price: 25000,
    fuelType: "Gasoline",
    transmission: "Automatic",
    engine: "2.0L 4-cylinder",
    horsepower: 169,
    features: ["Bluetooth", "Backup Camera", "Keyless Entry"],
    owners: 1,
    image:
      "https://autoreview.ru/images/gallery/%D0%9D%D0%BE%D0%B2%D0%BE%D1%81%D1%82%D0%B8/2022/June/02/toyota-corolla-eu3.jpg",
  },
  {
    id: 2,
    make: "Honda",
    model: "Civic",
    year: 2021,
    color: "Gray",
    mileage: 18000,
    price: 22000,
    fuelType: "Gasoline",
    transmission: "CVT",
    engine: "1.5L 4-cylinder",
    horsepower: 158,
    features: ["Apple CarPlay", "Android Auto", "Lane Departure Warning"],
    owners: 2,
    image: "https://autoiwc.ru/images/honda/honda-civic.webp",
  },
  {
    id: 3,
    make: "Ford",
    model: "Mustang",
    year: 2020,
    color: "Orange",
    mileage: 15000,
    price: 35000,
    fuelType: "Gasoline",
    transmission: "Manual",
    engine: "5.0L V8",
    horsepower: 450,
    features: ["Leather Seats", "Navigation System", "Heated Seats"],
    owners: 1,
    image: "https://a.d-cd.net/lUAAAgAbPOA-1920.jpg",
  },
  {
    id: 4,
    make: "Chevrolet",
    model: "Equinox",
    year: 2019,
    color: "Orange",
    mileage: 30000,
    price: 20000,
    fuelType: "Gasoline",
    transmission: "Automatic",
    engine: "1.5L 4-cylinder",
    horsepower: 170,
    features: ["Rearview Camera", "Blind-Spot Monitoring", "Wi-Fi Hotspot"],
    owners: 2,
    image:
      "https://s.auto.drom.ru/i24246/c/photos/fullsize/chevrolet/equinox/chevrolet_equinox_957846.jpg",
  },
  {
    id: 5,
    make: "Nissan",
    model: "Altima",
    year: 2020,
    color: "white",
    mileage: 22000,
    price: 21000,
    fuelType: "Gasoline",
    transmission: "CVT",
    engine: "2.5L 4-cylinder",
    horsepower: 188,
    features: ["Remote Start", "Automatic Emergency Braking", "Lane Keeping Assist"],
    owners: 1,
    image:
      "https://media.ed.edmunds-media.com/nissan/altima/2020/oem/2020_nissan_altima_sedan_25-platinum_fq_oem_1_1600.jpg",
  },
  {
    id: 6,
    make: "BMW",
    model: "3 Series",
    year: 2021,
    color: "Gray",
    mileage: 12000,
    price: 40000,
    fuelType: "Diesel",
    transmission: "Automatic",
    engine: "2.0L 4-cylinder",
    horsepower: 255,
    features: ["Sunroof", "Adaptive Cruise Control", "Parking Assistance"],
    owners: 1,
    image: "https://www.topgear.com/sites/default/files/2022/09/1-BMW-3-Series.jpg",
  },
  {
    id: 7,
    make: "Tesla",
    model: "Model 3",
    year: 2022,
    color: "Red",
    mileage: 8000,
    price: 45000,
    fuelType: "Electric",
    transmission: "Automatic",
    engine: "Electric Motor",
    horsepower: 322,
    features: ["Autopilot", "Full Self-Driving Capability", "Premium Audio System"],
    owners: 1,
    image: "https://cdn.motor1.com/images/mgl/x7rpz/s1/4x3/tesla-model-3.webp",
  },
  {
    id: 8,
    make: "Audi",
    model: "Q5",
    year: 2021,
    color: "Blue",
    mileage: 15000,
    price: 38000,
    fuelType: "Gasoline",
    transmission: "Automatic",
    engine: "2.0L 4-cylinder",
    horsepower: 248,
    features: ["Virtual Cockpit", "Panoramic Sunroof", "Apple CarPlay"],
    owners: 1,
    image: "https://www.allcarz.ru/wp-content/uploads/2021/03/foto-q5-2021-price_02.jpg",
  },
  {
    id: 9,
    make: "Mercedes-Benz",
    model: "E-Class",
    year: 2020,
    color: "Silver",
    mileage: 18000,
    price: 42000,
    fuelType: "Gasoline",
    transmission: "Automatic",
    engine: "2.0L 4-cylinder",
    horsepower: 255,
    features: ["MBUX Infotainment", "Heated Steering Wheel", "Air Suspension"],
    owners: 2,
    image: "https://rg.ru/uploads/images/183/62/20/53.jpg",
  },
  {
    id: 10,
    make: "Chevrolet",
    model: "Tahoe",
    year: 2020,
    color: "Black",
    mileage: 25000,
    price: 45000,
    fuelType: "Gasoline",
    transmission: "Automatic",
    engine: "5.3L V8",
    horsepower: 355,
    features: ["Leather Seats", "Third-Row Seating", "Power Liftgate"],
    owners: 2,
    image: "https://autopremiumgroup.ru/m/_versions/info/chevrolet/tahoe/2020/14_banner.jpg",
  },
  {
    id: 11,
    make: "Subaru",
    model: "Outback",
    year: 2021,
    color: "Brown",
    mileage: 12000,
    price: 32000,
    fuelType: "Gasoline",
    transmission: "CVT",
    engine: "2.5L 4-cylinder",
    horsepower: 182,
    features: ["All-Wheel Drive", "Roof Rails", "Adaptive Cruise Control"],
    owners: 1,
    image:
      "https://autoreview.ru/images/gallery/%D0%9D%D0%BE%D0%B2%D0%BE%D1%81%D1%82%D0%B8/2021/March/29/subaru-outback2.jpeg",
  },
  {
    id: 12,
    make: "Lexus",
    model: "RX 350",
    year: 2022,
    color: "White",
    mileage: 8000,
    price: 48000,
    fuelType: "Gasoline",
    transmission: "Automatic",
    engine: "3.5L V6",
    horsepower: 295,
    features: ["Premium Leather Seats", "Panoramic Sunroof", "Mark Levinson Audio"],
    owners: 1,
    image:
      "https://carsguide-res.cloudinary.com/image/upload/f_auto%2Cfl_lossy%2Cq_auto%2Ct_default/v1/editorial/2022-Lexus-RX-350-F-Sport-1001x565.jpg",
  },
  {
    id: 13,
    make: "BMW",
    model: "X5",
    year: 2021,
    color: "Black",
    mileage: 14000,
    price: 55000,
    fuelType: "Diesel",
    transmission: "Automatic",
    engine: "3.0L 6-cylinder",
    horsepower: 335,
    features: ["Heated Seats", "Wireless Charging", "Gesture Control"],
    owners: 1,
    image:
      "https://mfair.ua/user/cars/53372/53372-new-oficial-vnedorozhnik-bmw-x5-m30d-kiev-2021-top.jpeg",
  },
  {
    id: 14,
    make: "Tesla",
    model: "Model Y",
    year: 2022,
    color: "White",
    mileage: 8000,
    price: 52000,
    fuelType: "Electric",
    transmission: "Automatic",
    engine: "Dual Electric Motors",
    horsepower: 384,
    features: ["Autopilot", "Premium Interior", "Panoramic Roof"],
    owners: 1,
    image:
      "https://bex-auto.com/storage/products/4030/resizedcrop-f88fa6aa9ec5719bf096d3a4df64732a-840x480-1.jpg",
  },
  {
    id: 15,
    make: "Mercedes-Benz",
    model: "GLE 350",
    year: 2020,
    color: "Black",
    mileage: 18000,
    price: 46000,
    fuelType: "Gasoline",
    transmission: "Automatic",
    engine: "2.0L 4-cylinder",
    horsepower: 255,
    features: ["MBUX Infotainment", "Panoramic Sunroof", "Adaptive Cruise Control"],
    owners: 2,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Mercedes-Benz_GLE_350_d_4MATIC_AMG_Line_%28V_167%29_%E2%80%93_h_09022020.jpg/1200px-Mercedes-Benz_GLE_350_d_4MATIC_AMG_Line_%28V_167%29_%E2%80%93_h_09022020.jpg",
  },
];
